
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Python Setup'
      uses: 'actions/setup-python@v5'
      with:
        python-version: '3.13.0'

    - name: 'Install Dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Login to Docker Hub'
      uses: 'docker/login-action@v1'
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: 'Docker Hub Upload'
      env:
        NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        REPO: 'kiel0103/2024-ecr-python-test'
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:$IMAGE_TAG
        docker push $NAME/$REPO:$IMAGE_TAG
